export const CUSTOMER_ADDED = "CUSTOMER_ADDED";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";
export const CUSTOMER_REMOVED = "CUSTOMER_REMOVED";
export const ACCEPTING_CHANGED = "ACCEPTING_CHANGED";
